### ISSUE TITLE
Incorrect Guide Data for SBS Viceland HD and SBS World Movies

### ISSUE THREAD

**Issue by adelavig** [ShephedProject/shepherd#13]
I am using the W.A. Regional (102) region.

The program data for "SBS Viceland HD" channel contains the program data for "SBS World Movies" and there does not seem to be a choice to select "SBS World Movies" during the channel setup section of the --configure process.

So the upshot is my guide data for channel 31 "SBS Viceland HD" (SBSVicelandHD.shepherd.com) contains the data for "SBS World Movies" and channel 32 "SBS World Movies" (no XMLID) contains no data.

This may be a work in progress since the switchover happened in the 1st of July but since I didn't see an issue raised, I thought I'd raise one.

**Comment by Maliuta** [comment]
I just re-scanned my Myth install to pickup the "SBS World Movies" channel. I'm in Brisbane (region 75). I haven't had any issues with the "SBS Viceland HD" guide data. Although there is still a lack of data for "SBS World Movies"

Region 75. 29 MythTV channels. 20 Shepherd channels.

   #  MythTV Channel                 Shepherd Guide Data
 --------------------------------------------------------
  11  10 Peach                       <- 10 Peach
  12  10 Boss                        <- 10 Bold
  13  10 HD                          <- 10 HD
  20  ABC HD                         <- ABC HD
  22  ABCComedy/Kids                 <- ABC COMEDY/ABC KIDS
  23  ABC ME                         <- ABCME
  24  ABC NEWS                       <- ABCNEWS
  30  SBS ONE HD                     <- SBS HD
  31  SBS VICELAND HD                <- SBSVICELANDHD
  32  SBS World Movies               <- SBSVICELAND
  33  SBS Food                       <- SBS Food
  34  NITV                           <- NITV
  36  SBS Arabic24                   <- -
  37  SBS Radio 1                    <- -
  38  SBS Radio 2                    <- -
  39  SBS Radio 3                    <- -
  70  7HD Brisbane                   <- 7HD
  72  7TWO Brisbane                  <- 7TWO
  73  7mate Brisbane                 <- 7mate
  74  7food network                  <- 7food network
  76  7flix Brisbane                 <- 7flix
  90  9HD Brisbane                   <- 9HD
  95  9Gem HD Brisbane               <- 9Gem
  99  9Go!                           <- 9Go!
 200  Double J                       <- -
 201  ABC Jazz                       <- -
 305  SBS PopDesi                    <- -
 306  SBS Chill                      <- -
 307  SBS PopAsia                    <- -`

**Comment by adelavig** [comment]
When I run a channel configure of shepherd for region 102 , I don't see a choice for World Movies. I can only see SBS, SBS HD, SBS Food, SBSVICELAND and SBSVICELANDHD.

I've set up Shepherd so SBS Viceland HD uses "SBSVICELANDHD" and World Movies uses "SBSVICELAND". Both channels have the same guide data, which is the World Movies data. The funny thing is that after Wednesday's run (24th July), SBS Viceland HD actually had the correct data after the 30th of July for about 2 days but after today's run (25th July), all the data has reverted back to World Movies.

**Comment by adelavig** [comment]
I've just checked the ancestry of a random program on SBS Viceland HD and the data is coming from the OzTivo grabber. I've just checked the OzTivo site but I can't tell which channel the data is coming from. OzTivo does have "S3-Perth-SBSVICELANDHD" and S3-Perth-SBSWorldMovies" channels, each with the correct data. Is there a way I can map these OzTivo channels in Shepherd to the XLMTV ids I need?

**Comment by adelavig** [comment]
After Friday's run (26th July) the data for VicelandHD was identical to World Movies until 1:00am 1st August. After that, there was no more data for World Movies but VicelandHD had a further 2 days worth of data that was correct. I checked the ancestry for 2:00am on the 1st of August and the VicelandHD data was coming from Rex, whereas the data before that time when the channels had the same data came from OzTivo. 

This lead me to think that the OzTivo data was somehow overwriting the Rex data, so I did "--set-component shepherd:grabwith=rex" and reran shepherd with the --no-timetest option to regrab all data. After it finished, the data for VicelandHD and World Movies was now correct for both channels. So it looks like the issue is with the OzVito grabber config.

This is my channel config:
Region 102. 27 MythTV channels. 23 Shepherd channels.

   #  MythTV Channel                 Shepherd Guide Data
 --------------------------------------------------------
   1  Bold                           <- WIN Bold
   2  ABC                            <- ABC
   3  SBS ONE                        <- SBS
   7  GWN7                           <- GWN7
   9  Nine                           <- Nine
  10  WIN                            <- WIN
  11  Peach                          <- WIN Peach
  13  WIN HD                         <- WIN HD
  14  TVSN                           <- TVSN
  20  ABC HD                         <- ABC
  21  ABC                            <- ABC
  22  ABCComedy/Kids                 <- ABC COMEDY/ABC KIDS
  23  ABC Me                         <- ABCME
  24  ABC News                       <- ABCNEWS
  30  SBS One HD                     <- SBS HD
  31  SBS Viceland HD                <- SBSVICELANDHD
  32  SBS World Movies               <- SBSVICELAND
  33  SBS Food                       <- SBS Food
  34  NITV                           <- NITV
  54  Ch-54                          <- -
  65  ishoptv                        <- -
  71  7two                           <- 7TWO
  73  7mate                          <- 7mate
  78  Racing.com                     <- RACING.COM
  83  Sky News on WIN                <- Sky News
  92  Gem                            <- GEM
  99  Go!                            <- GO!

**Comment by thiakil** [comment]
I've released some channel updates, please let me know if they help or need more work

**Comment by adelavig** [comment]
> I've released some channel updates, please let me know if they help or need more work

Thanks for the update.

I ran a --configure and could see a "SBS World Movies" selection, so I reconfigured channel 32 (World Movies) to use that and kept 31 (VicelandHD) as SBSVicelandHD and reran the script after removing the grabwith=rex option. The results however are the same, 31 and 32 both have the SBS World Movies data.

**Comment by jziv** [comment]
The update has fixed the missing "SBS World Movies" issue for me.  Region 73 (sydney).

```
Thank you!

Region 73. 36 MythTV channels. 27 Shepherd channels.

   #  MythTV Channel                 Shepherd Guide Data
 --------------------------------------------------------
  31  SBS VICELAND HD              <- SBSVICELANDHD
  32  SBS World Movies               <- SBS World Movies
```

**Comment by thiakil** [comment]
@adelavig can you please run a `tv_grab_au  --show-config` and post the output here?

Please use a code block when pasting. E.g.

\`\`\`
\<paste\>
\`\`\`

**Comment by adelavig** [comment]
Sure thing thiakil, config below.

Also, as a test I reran shepherd with the --grabwith=rex option again and got the correct listings for SBSVicelandHD.

```
[mythtv@zocolo ~]$ tv_grab_au --show-config
shepherd v1.9.13 (linux)

Reading configuration file: /home/mythtv/.shepherd/shepherd.conf
Reading channels file: /home/mythtv/.shepherd/channels.conf

Configuration
-------------
Config file: /home/mythtv/.shepherd/shepherd.conf
Debug mode : No
Output file: None
Region ID  : 102

Attempting Mysql connection to MythTV database mythconverg.
Looking for MythTV DB connection info in /home/mythtv/.mythtv/config.xml.
Using MythTV DB settings from: /home/mythtv/.mythtv/config.xml

Region 102. 27 MythTV channels. 23 Shepherd channels.

   #  MythTV Channel                 Shepherd Guide Data
 --------------------------------------------------------
   1  Bold                           <- WIN Bold
   2  ABC                            <- ABC
   3  SBS ONE                        <- SBS
   7  GWN7                           <- GWN7
   9  Nine                           <- Nine
  10  WIN                            <- WIN
  11  Peach                          <- WIN Peach
  13  WIN HD                         <- WIN HD
  14  TVSN                           <- TVSN
  20  ABC HD                         <- ABC
  21  ABC                            <- ABC
  22  ABCComedy/Kids                 <- ABC COMEDY/ABC KIDS
  23  ABC Me                         <- ABCME
  24  ABC News                       <- ABCNEWS
  30  SBS One HD                     <- SBS HD
  31  SBS Viceland HD                <- SBSVICELANDHD
  32  SBS World Movies               <- SBS World Movies
  33  SBS Food                       <- SBS Food
  34  NITV                           <- NITV
  54  Ch-54                          <- -
  65  ishoptv                        <- -
  71  7two                           <- 7TWO
  73  7mate                          <- 7mate
  78  Racing.com                     <- RACING.COM
  83  Sky News on WIN                <- Sky News
  92  Gem                            <- GEM
  99  Go!                            <- GO!


                         Enabled/
 Grabber         Version Ready  Last Run  Status
 --------------- ------- ----- ---------- -------------------------------------
 abc_website        7.02 Y/Y      5:04pm  0ch/0pr/0hrs no-data
 oztivo             2.63 Y/Y      5:03pm  14ch/3369pr/2337hrs Sat27Jul-Mon05Aug
 sbsweb             5.05 Y/Y      4:59pm  5ch/1223pr/961hrs Sun28Jul-Mon05Aug
 rex             10.4.11 Y/Y      4:57pm  23ch/5475pr/3839hrs Sun28Jul-Sun04Aug
 foxtel_swf         5.02 Y/Y        -     Failed (code 255)
 freeview          1.0.4 Y/Y        -     Failed (code 10)

 Reconciler
 --------------- ------- ----- ---------- -------------------------------------
 reconciler_mk2     0.58 Y/Y      5:06pm  23ch/5878pr/4104hrs Sat27Jul-Mon05Aug

 Postprocessor
 --------------- ------- ----- ---------- -------------------------------------
 metacritic          1.1 Y/Y      5:14pm  23ch/5878pr/4104hrs Sat27Jul-Mon05Aug
 augment_timezone   0.30 Y/Y      5:07pm  23ch/5878pr/4104hrs Sat27Jul-Mon05Aug
 add_channel_ic..    0.2 Y/Y      5:06pm  23ch/5878pr/4104hrs Sat27Jul-Mon05Aug
Shepherd last ran successfully 3h27m ago and acquired 91.96% of data.
```

**Comment by thiakil** [comment]
Ah, so all is good now? Bit of an odd one

**Comment by adelavig** [comment]
Well, yes and no. I have correct data for Viceland, but a bunch of my recording rules don't work now because some of the program names have changed e.g. "Q & A" vs "Q&A".

I got the --grabwith tip from the "HDTV" part of the wiki. I got the impression that it was only for temporary use until issues with shepherd were fixed.

**Comment by thiakil** [comment]
Alrighty. Generally the reconciler should take care of the titles such as that. If it's not then probably time for a new issue thread. 

Does the title mismatch happen only with Rex, or are you forcing Rex to get the matching titles?

> I got the impression that it was only for temporary use until issues with shepherd were fixed.

Yes, generally it's expected that you let Shepherd decide which grabber is run first, which it does based on a priority system of quality. Rex is one of the higher quality ones though so it's probably not a huge deal to use it

**Comment by adelavig** [comment]
> Does the title mismatch happen only with Rex, or are you forcing Rex to get the matching titles?

The mismatch happens when I use --grabwith=rex, that's the only change I made. I don't know how to force Rex to get matching titles. I did however reconfigure Shepherd to migrate titles from OzTivo but that didn't make a difference, the titles were still different.

This does still point to the issue that OzTivo and Rex are returning totally different data for SBSVicelandHD, with OzTivo returning the titles for World Movies. However, as I mentioned above the "S3-Perth-SBSVICELANDHD" channel on OzTivo has correct data. Can you get OzTivo to grab the titles from that channel instead of the one being used now?

**Comment by thiakil** [comment]
As far as I can see, the only way you would have got World Movies data for `VICELAND` is if OzTivo had some bad data (which is entirely possible as they have their own upstream grabbers).

Our OzTivo grabber _doesn't have_ a `SBS World Movies` mapping at the moment - I need to do some more work on it.

`SBSVICELANDHD`  (and `SBSVICELAND`) are mapped to OzTivo `SBSTWO-<state>` (which the aforementioned `S3-Perth-SBSVICELANDHD` is derived from) and from what I can see `SBSTWO-WA` has the correct data _now_.

If there are more titles than Q&A that are failing to be recognised by the reconciler, please open an issue with a list of them and I'm sure we can add some default rules so others can benefit. I would advise you remove the forced `rex` now too. That way you can benefit from the Freeview grabber update that will be pushed out soon

**Comment by adelavig** [comment]
I have removed the --grabwith=rex option and confirmed in the log that shepherd is now choosing the best grabber. Viceland and World Movies now have the correct listings (I even emptied the program table in MythTV to make sure).

There is still the issue with the naming of a few programs, so I opened an new issue as suggested.

Thanks for all your help.

**Comment by thiakil** [comment]
Good to hear!

**Comment by drfarmerdave** [comment]
Hi,
I realise this issue has been closed, but I'm still not getting an option to include SBS World Movies for Adelaide (region 81). My grabber is up to date, and running with --configure gives
```
Guide data sources:
( 0) (no guide)                    (16) ABC                           
( 1) 10                            (17) ABC COMEDY/ABC KIDS           
( 2) 10 Bold                       (18) ABC HD                        
( 3) 10 HD                         (19) ABCME                         
( 4) 10 Peach                      (20) ABCNEWS                       
( 5) 44Adelaide                    (21) NITV                          
( 6) 7HD                           (22) Nine                          
( 7) 7TWO                          (23) RACING.COM                    
( 8) 7flix                         (24) SBS                           
( 9) 7food network                 (25) SBS Food                      
(10) 7mate                         (26) SBS HD                        
(11) 9Gem                          (27) SBSVICELANDHD                 
(12) 9Gem HD                       (28) Seven                         
(13) 9Go!                          (29) SpreeTV                       
(14) 9HD                           (30) TVSN                          
(15) 9Life                         
MythTV channel 32: SBS World Movies [default=0 (no guide)] ? 
```

**Comment by drfarmerdave** [comment]
```
~/.shepherd/shepherd --show-config
shepherd v1.9.13 (linux)

Reading configuration file: /home/david/.shepherd/shepherd.conf
Reading channels file: /home/david/.shepherd/channels.conf

Configuration
-------------
Config file: /home/david/.shepherd/shepherd.conf
Debug mode : No
Output file: None
Region ID  : 81

Attempting Mysql connection to MythTV database mythconverg.
Looking for MythTV DB connection info in /home/david/.mythtv/config.xml.
Using MythTV DB settings from: /home/david/.mythtv/config.xml

Region 81. 36 MythTV channels. 29 Shepherd channels.

   #  MythTV Channel                 Shepherd Guide Data
 --------------------------------------------------------
   1  10 BOLD                        <- 10 Bold
   2  ABC                            <- ABC
   3  SBS ONE                        <- SBS
   7  7 Adelaide                     <- Seven
   9  Channel 9 Adelaide             <- Nine
  10  10                             <- 10
  11  10 Peach                       <- 10 Peach
  12  10 BOLD                        <- 10 Bold
  13  10 HD                          <- 10 HD
  14  TVSN                           <- TVSN
  15  SpreeTV                        <- SpreeTV
  20  ABC HD                         <- ABC HD
  21  ABC                            <- ABC
  22  ABCComedy/Kids                 <- ABC COMEDY/ABC KIDS
  23  ABC ME                         <- ABCME
  24  ABC NEWS                       <- ABCNEWS
  30  SBS ONE HD                     <- SBS HD
  31  SBS VICELAND HD                <- SBSVICELANDHD
  32  SBS World Movies               <- -
  33  SBS Food                       <- SBS Food
  34  NITV                           <- NITV
  70  7HD Adelaide                   <- 7HD
  71  7 Adelaide                     <- Seven
  72  7TWO Adelaide                  <- 7TWO
  73  7mate Adelaide                 <- 7mate
  74  7food network                  <- 7food network
  75  openshop                       <- -
  76  7flix Adelaide                 <- 7flix
  78  RACING.COM                     <- RACING.COM
  90  9HD Adelaide                   <- 9HD
  91  Channel 9 Adelaide             <- Nine
  92  9Gem Adelaide                  <- 9Gem
  93  9Go! Adelaide                  <- 9Go!
  94  9Life Adelaide                 <- 9Life
  95  9Gem HD Adelaide               <- 9Gem HD
  99  9Go! Adelaide                  <- 9Go!


                         Enabled/
 Grabber         Version Ready  Last Run  Status
 --------------- ------- ----- ---------- -------------------------------------
 rex             10.4.11 Y/Y      6:36pm  9ch/474pr/216hrs Fri01Nov-Sat02Nov
 foxtel_swf         5.02 Y/Y      6:35pm  20ch/708pr/757hrs Fri01Nov-Sat02Nov
 abc_website        7.02 Y/Y   Thu 31-Oct 0ch/0pr/0hrs no-data
 oztivo             2.63 Y/Y   Thu 31-Oct 19ch/3488pr/2386hrs Thu31Oct-Fri08Nov
 sbsweb             5.05 Y/Y    08-Apr-19 4ch/1170pr/767hrs Mon08Apr-Tue16Apr
 yahoo7widget       2.44 N/Y    19-Sep-17 centrally disabled
 freeview          1.0.4 Y/Y        -     Failed (code 10)
 zaxmltv            0.03 N/Y        -     centrally disabled
 acctv_website      0.09 N/Y        -     centrally disabled

 Reconciler
 --------------- ------- ----- ---------- -------------------------------------
 reconciler_mk2     0.58 Y/Y      6:37pm  29ch/1042pr/721hrs Fri01Nov-Sat02Nov

 Postprocessor
 --------------- ------- ----- ---------- -------------------------------------
 the_movie_db_a..    1.0 Y/Y      6:41pm  29ch/1042pr/721hrs Fri01Nov-Sat02Nov
 metacritic          1.1 Y/Y      6:40pm  29ch/1042pr/721hrs Fri01Nov-Sat02Nov
 augment_timezone   0.30 Y/Y      6:37pm  29ch/1042pr/721hrs Fri01Nov-Sat02Nov
 add_channel_ic..    0.2 Y/Y      6:37pm  29ch/1042pr/721hrs Fri01Nov-Sat02Nov
 imdb_augment_d..   1.03 N/Y    30-Mar-19 centrally disabled
Shepherd last ran successfully 22h33m ago and acquired 96.82% of data.
Shepherd last autorefreshed 1h12m ago.
```
