### ISSUE TITLE
Shepherd Integration with Plex

### ISSUE THREAD

**Issue by chris-jennings** [ShephedProject/shepherd#14]
Now that Plex has stuffed the EPG data for Australian users I have come back to Shepherd for a look. I used it for many years with MythTV and I found it to be a great source of EPG data.

I installed it and it runs, reconciles data correctly but it doesn't work nicely with Plex. All programs are detected as "Movies" unless episode data is included. This means that the PVR functions incorrectly when you want to record multiple episodes because if it is a movie you only need to record it once.

There is another project which makes a xmltv file with the correct format here:
[https://github.com/markcs/freeview_xmltv](https://github.com/markcs/freeview_xmltv)

I will start looking at how to add this function myself but I have limited time, and I imagine there are a lot of other people in the same position with Plex and I wanted to check what other people are doing.

**Comment by thiakil** [comment]
Hiya Chris,

I'm not familiar with how Plex determines episode vs movie, but many of our guide data sources just don't give us the information needed to put episode/series numbers in.

We do also have our own Freeview grabber, but their data is still broken for anyone not in AEST/AEDT as some channels aren't timeshifted. As a result the update from their last format change hasn't been pushed out
