### ISSUE TITLE
Perl Dependencies for Ubuntu 20.04

### ISSUE THREAD

**Issue by fleasidewinder** [ShephedProject/shepherd#19]
Hi,
Following is the start of the installation of shepherd and feedback from terminal entry.
As you can see at the bottom of the data one of the dependencies gets substituted and no substitute is found for another.
If you carry out the dependency install and then "perl shepherd" it wont install properly due to missing dependency. I am not sure if the subtitled dependency is also correct.
All install information is followed from the github installation manual.
https://github.com/ShephedProject/shepherd/wiki/Installation#steps---new-installations
Perl Dependencies are supported in Ubuntu 19.10 but not in 20.04.
------------------------------------------------------------------------------------------------------------------------------------
:~$ wget 'https://raw.githubusercontent.com/ShephedProject/shepherd/release/applications/shepherd'
--2020-05-05 03:30:46-- https://raw.githubusercontent.com/ShephedProject/shepherd/release/applications/shepherd
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.28.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.28.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 165116 (161K) [text/plain]
Saving to: 'shepherd’

shepherd 100%[===================>] 161.25K --.-KB/s in 0.05s

2020-05-05 03:30:46 (3.37 MB/s) - 'shepherd’ saved [165116/165116]

:~$ sudo apt-get install libxml-simple-perl libalgorithm-diff-perl \libgetopt-mixed-perl libdata-dumper-simple-perl libdate-manip-perl \liblist-compare-perl libdatetime-format-strptime-perl \libhtml-parser-perl libxml-dom-perl libgd-gd2-perl libarchive-zip-perl \libio-string-perl xmltv libdbi-perl libsort-versions-perl libjson-perl libobject-tiny-perl
[sudo] password for mark:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libgd-perl' instead of 'libgd-gd2-perl'
E: Unable to locate package libgetopt-mixed-perl
------------------------------------------------------------------------------------------------------------------------------------
Kind regards,
Mark

**Comment by willat8** [comment]
I've backported the package to 20.04 as a temporary fix in this ppa https://launchpad.net/~willat8/+archive/ubuntu/shepherd
Edit: this is the discussion where the package was deprecated https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=948208

**Comment by fleasidewinder** [comment]
Replacing **libgd-gd2-perl** with **libgd-perl** is ok for Shepherd

**Comment by fleasidewinder** [comment]
Hi,
Added ppa to system but Shepherd still has issues with perl dependencies.
When trying to install shepherd the following dependency failed.
---------------------------------------------------------------------------
Downloading the_movie_db_augment v1.0.
Testing postprocessor the_movie_db_augment ... FAIL.

Postprocessor the_movie_db_augment did not exit cleanly!
Probably failed due to dependency on missing module 'Locale::Codes::Country'

<<<<<< output from the_movie_db_augment was as follows:
Can't locate Locale/Codes/Country.pm in @INC (you may need to install the Locale::Codes::Country module) (@INC contains: /home/mark/.shepherd/references /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/mark/.shepherd/references/TMDB.pm line 433.
BEGIN failed--compilation aborted at /home/mark/.shepherd/references/TMDB.pm line 433.
Compilation failed in require at /home/mark/.shepherd/postprocessors/the_movie_db_augment/the_movie_db_augment-1.0 line 14.
BEGIN failed--compilation aborted at /home/mark/.shepherd/postprocessors/the_movie_db_augment/the_movie_db_augment-1.0 line 14.
>>>>>> end output from the_movie_db_augment

the_movie_db_augment v1.0 failed ready test - marking as a pending update.
------------------------------------------------------------------------------------
Kind regards,
Mark

**Comment by fleasidewinder** [comment]
It appears replacing perl dependency **libgd-gd2-perl** with **libgd-perl** causes issues with the above **movie_db_augment v1.0**
Kind regards,
Mark

**Comment by willat8** [comment]
You may need to install `liblocale-codes-perl` too.

This is my set up https://hub.docker.com/r/willat8/shepherd/dockerfile

**Comment by fleasidewinder** [comment]
Ok. Thanks I will try.

**Comment by fleasidewinder** [comment]
Thank you **willat8** Ubuntu 20.04 with Mythtv 31 and **shepherd** setup as per the above has installed, configured and operating great now.
I don't quite understand your shepherd dockerfile as I am not a coder but will review and see if I can understand it. 
Thanks again for your help and information.
I will link this discussion in other areas too as others have also had same problem.
Kind regards,
Mark

**Comment by fleasidewinder** [comment]
There is no need to add a ppa anymore as it as been updated as per the following https://launchpad.net/~willat8/+archive/ubuntu/shepherd/+packages.
So installing listed dependencies in installing guide will now install properly as of 15/09/2021. 
Thanks to great work of "willat8".

**Comment by thiakil** [comment]
Shepherd uses `Getopt::Long`, not `Getopt::Mixed` as far as I can tell.

As far as I can tell, that should be built into perl

**Comment by willat8** [comment]
Confirmed working without libgetopt-mixed-perl (I've deleted the PPA too). I think liblocale-codes-perl is still needed though (and it's not mentioned in the wiki).

**Comment by willat8** [comment]
On that topic, I think the following are needed (in addition to what's listed on the wiki):

```
libjson-maybexs-perl
libdbd-mysql-perl
liblocale-codes-perl
```

**Comment by thiakil** [comment]
added `libdbd` and `liblocale`

`libjson-maybexs` isnt directly used, we need at least `libjson-perl` and one of the supported engines `JSON::PP` or `JSON::XS`

Ubuntu [recommends](https://packages.ubuntu.com/focal/libjson-perl) `libjson-xs-perl` so I'll add it

I'm not sure `libgd-perl` is used, so I'm going to remove that one

**Comment by willat8** [comment]
Yep works well
