### ISSUE TITLE
Please add 9Rush to channel_list.yml

### ISSUE THREAD

**Issue by Bernmeister** [ShephedProject/shepherd#20]
According to [Wikipedia](https://en.wikipedia.org/wiki/9Rush) the regions supported are:

- 73:
    state: NSW
    name: "Sydney"

-   94:
    state: VIC
    name: "Melbourne"

-   75:
    state: QLD
    name: "Brisbane"

-   255:
    state: QLD
    name: "Sunshine Coast"

-   81:
    state: SA
    name: "Adelaide"

-   101:
    state: WA
    name: "Perth"
    timezone: Australia/Perth

-   342:
    state: WA
    name: Mandurah

**Comment by MrEggy** [comment]
I would very much second a request for support for 9Rush.  Thanks.

**Comment by ghost** [comment]
I'm working on an update.  Using data from yourtv.com.au I have found 9Rush in the following regions:
101: Perth
255: Sunshine Coast
66: Central Coast
73: Sydney
75: Brisbane
81: Adelaide
94: Melbourne

**Comment by MrEggy** [comment]
Hi TerribleTadpole.  Did you complete your update?

**Comment by thiakil** [comment]
Hi folks, I added 9rush to a bunch of regions the other day, let me know if I missed any

NB: the yaml file isn't really used. It was intended to perhaps be used to generate the channel file that shep uses, but the idea never really eventuated
