### ISSUE TITLE
PERL5LIB overwritten - breaks on Perlbrew install

### ISSUE THREAD

**Issue by Flic182** [ShephedProject/shepherd#21]
I've run Shepherd for years with system Perl, but would now like to use Perlbrew.  I've been able to install all required modules under my Perlbrew-managed Perl, but I noticed a problem at line 1697 of shepherd:
```
my $exec = sprintf "PERL5LIB=\"%s/references\" %s 2>&1|", $CWD, $prog;
```
This clobbers the PERL5LIB environment variable.  Unfortunately, that is exactly where all the XMLTV modules go when it is installed via `make`.  Consequently, shepherd complains several required modules are missing from `@INC` (primarily XMLTV, but a couple of others as well).

My guess is this line was put there for security purposes by enforcing a known environment.  If so, how critical is this?  Would it be possible to do this instead:
```
my $exec = sprintf "PERL5LIB=\"$ENV{PERL5LIB}:%s/references\" %s 2>&1|", $CWD, $prog;
```

That way, the user's existing `$PERL5LIB` is respected and the necessary `references` directory is merely appended.  As far as I can tell, shepherd still seems to work with this modification.

**Comment by thiakil** [comment]
It's how Shepherd injects its own shipped helper modules. I've made some modifications that should help you out
