### ISSUE TITLE
the --set-icons option doesn't get logo_list.txt correctly

### ISSUE THREAD

**Issue by daehenoc** [ShephedProject/shepherd#24]
Hi,

I used the --set-icons option to get TV channel icons, and noticed that shepherd attempts to download the logo_list.txt web page from github, instead of the raw logo_list.txt file.  Here is the patch that fixes this issue:

--- postprocessors/add_channel_icons/add_channel_icons.orig	2020-10-27 17:56:24.973306809 +1000
+++ postprocessors/add_channel_icons/add_channel_icons	2020-10-27 17:56:53.033496924 +1000
@@ -148,7 +148,7 @@
 sub load_logo_list
 {
     # fetch icon styles
-    $icon_styles = &Shepherd::Common::get_url('http://github.com/ShephedProject/shepherd/blob/release/logo_list.txt');
+    $icon_styles = &Shepherd::Common::get_url('http://raw.githubusercontent.com/ShephedProject/shepherd/release/logo_list.txt');
     exit 1 unless ($icon_styles);
 
     foreach my $line (split/\n/,$icon_styles)

Cheers!

**Comment by thiakil** [comment]
This was solved already by #18
