### ISSUE TITLE
channel_list updates for Newcastle, NSW

### ISSUE THREAD

**Issue by dscoular** [ShephedProject/shepherd#27]
Hi,
While I'm not certain how wide this problem is, I do know that it impacts region 184 (NSW: Newcastle).

Ownership of channel Ten appears to have been transferred from WIN to Souther Cross while channel Nine has moved to WIN.

This caused MythTV to replace all my channel Ten guide data with channel Nine.

The fix was to add the new Ten related entries (10,10 Bold,10 HD,10 Peach,10 Shake) to the line starting with the region number 184:

> ~/.shepherd/references/channel_list/channel_list
`184:10,10 Bold,10 HD,10 Peach,10 Shake,7flixPrime,7mate,7TWO,9Gem,9GO!,9HD,9Life,ABC TV,ABC Kids/ABC TV Plus,ABC TV HD,ABCME,ABCNEWS,Aspire,ishoptv,NBN,NITV,PRIME7,PRIME7 HD,RACING.COM,SBS,SBS Food,SBS HD,SB\
S World Movies,SBSVICELANDHD,Sky News,TVSN,WIN,WIN Bold,WIN HD,WIN Peach,WINGOLD`

I wasn't sure what was the best way to get this change incorporated into the latest shepherd.

Cheers,

Doug

**Comment by TheCook3** [comment]
It is similar for the ACT.  Channel 10 has come back.  We also have another channel 9 station coming soon.
https://www.canberratimes.com.au/story/7316079/july-1s-tv-flip-what-you-need-to-know/

You people out there that took over from Whuffy are doing a great job. I just wish I could understand half the code you people are cutting.

Taa,

Chris C

**Comment by TheCook3** [comment]
Hi,
thanks for fixing that.  I just can't find the change on my system.  Maybe I missed something in the update process.  I am using:
Checking for updates:
Source #1: https://raw.githubusercontent.com/ShephedProject/shepherd/release/
Source #2: https://raw.githubusercontent.com/ShephedProject/shepherd/release/

* Application shepherd v1.9.14...                              up to date
* Reference channel_list v149...                               up to date
* Reference DateTimeFormat/XMLTV.pm v1.001...                  up to date
* Reference Shepherd/FreeviewHelper.pm v1.3...                 up to date
* Reference TMDB.pm v1.2.1.1...                                up to date
* Reference Shepherd/Common.pm v1.33...                        up to date
* Reference Shepherd/json_pp.pm v0.2...                        up to date
* Reference Shepherd/Configure.pm v0.42...                     up to date
* Reference Shepherd/MythTV.pm v0.42...                        up to date
* Grabber rex v10.4.12...                                      up to date
* Grabber abc_website v7.04...                                 up to date
* Grabber sbsweb v5.05...                                      up to date
* Grabber foxtel_swf v5.04...                                  up to date
* Grabber oztivo v2.65...                                      up to date
* Reconciler reconciler_mk2 v0.58...                           up to date
* Postprocessor augment_timezone v0.30...                      up to date
* Postprocessor metacritic v1.1...                             up to date
* Postprocessor the_movie_db_augment v1.0...                   up to date
* Postprocessor add_channel_icons v0.4...                      up to date

Yet my channel_list still only shows:
126:7flixPrime,7mate,7TWO,9HD,9Life,ABC TV,ABC Kids/ABC TV Plus,ABC TV HD,ABCME,ABCNEWS,Aspire,GEM,GO!,ishoptv,Nine,NITV,PRIME7,PRIME7 HD,RACING.COM,SBN,SBS,SBS Food,SBS HD,SBS World Movies,SBSVICELANDHD,Sky News,TVSN,WIN,WIN Bold,WIN HD,WIN Peach,WINGOLD,Openshop

Not the channel 10 bits as shown in `https://github.com/ricksbrown/shepherd/commit/9151d8cfafe8a07b95b3440da1fd92e812a1efbb`

At the moment I am getting no data for channels 5, 50, 51, 52, 53, 54, 56, 81, 82 and 83.  I'm working on the 80s but can't get the 5/50s to work at all.

I tried to modify the channels_list file directly but that messed with the checksum.  I did get channel 5 data... none of the others.

I note that my two sources don't exist ie Source #1: https://raw.githubusercontent.com/ShephedProject/shepherd/release/ and
Source #2: https://raw.githubusercontent.com/ShephedProject/shepherd/release/ just give 400 errors.

Any hints on what I am doing wrong please.

Taa
Chris C

**Comment by glennmckechnie** [comment]
An interested user here. Certainly not authoritative, but I've been through this for some Victorian regional changes and have it working. So...

With these channel changes you need to update your local channel list at shepherds/references/channel_list (make a backup for sanity's sake). They have not been changed on the ShepherdProject GitHub release branch.

You've done this already judging by your comment regarding checksums and what you say is to be expected, shepherd will complain about the mismatch (because the release master hasn't been updated), but after your copy completes the terminal countdown (with warning) it will continue to run with the changes you've made.

If the planets align then you will get new data.
If they don't, then check the case of your changes and how they match with what your card / existing shepherd definitions are. 

> ( The following is only applicable if you are using area 90 [Ballarat, Victoria], but they show what changes worked for me...
>
>For instance, I found 9Go!, 9GO! and GO! in the channel_list. What worked for me in my channels.conf was ` 'GO!' => '9go!.shepherd.au',` 
> 
> Old channel_list entry...
> `90:7flixPrime,7mate,7TWO,9HD,9Life,ABC TV,ABC Kids/ABC TV Plus,ABC TV HD,ABCME,ABCNEWS,Aspire,GEM,GO!,ishoptv,Nine,NITV,PRIME7,PRIME7 HD,RACING.COM,SBN,SBS,SBS Food,SBS HD,SBS World Movies,SBSVICELANDHD,Sky News,TVSN,WIN,WIN Bold,WIN HD,WIN Peach,WINGOLD,Openshop`
> 
> New channel_list (working) entry...
> `90:7flixPrime,7mate,7TWO,9HD,9Life,ABC TV,ABC Kids/ABC TV Plus,ABC TV HD,ABCME,ABCNEWS,Aspire,9Gem,9Go!,ishoptv,Nine,NITV,PRIME7,PRIME7 HD,RACING.COM,SBN,SBS,SBS Food,SBS HD,SBS World Movies,SBSVICELANDHD,Sky News,TVSN,10,10 Bold,10 HD,10 Peach,10 SHAKE,WINGOLD,Openshop`
> )

YMMV. Hopefully not by too much.

Ah. Those sources do exist (as your update process works); They just don't work when plugged into a browser - Why? There's probably more to the URL than you see (via the script)

**Comment by TheCook3** [comment]
Thanks for that.   It is close to what I did but I may have messed up the
case stuff and when adding the channel_conf line.

I'll try it out keeping my fingers crossed.

Taa
Chris C

**Comment by glennmckechnie** [comment]
I probably should note (especially for other readers who may be taking this as gospel) that channel_conf is best done through the  `shepherd --configure` process when the .shepherd/channels.conf file will be created.

Certainly make a back up of the file (as always) to compare the changes and get a sense of what is going on behind the scene.
A small edit to the channel.conf file could then _probably_ be done by the more adventurous ;-)

cheers
  Glenn

**Comment by noisymime** [comment]
> > New channel_list (working) entry...
> > `90:7flixPrime,7mate,7TWO,9HD,9Life,ABC TV,ABC Kids/ABC TV Plus,ABC TV HD,ABCME,ABCNEWS,Aspire,9Gem,9Go!,ishoptv,Nine,NITV,PRIME7,PRIME7 HD,RACING.COM,SBN,SBS,SBS Food,SBS HD,SBS World Movies,SBSVICELANDHD,Sky News,TVSN,10,10 Bold,10 HD,10 Peach,10 SHAKE,WINGOLD,Openshop`
> > )

This worked a treated for me @glennmckechnie!
I'd started trying to figure out all the changes when I stumbled across this and found you'd already done the work. Thanks!

**Comment by thiakil** [comment]
Please double check your channels are correct in https://github.com/ShephedProject/shepherd/blob/master/references/channel_list as I've made a bunch of updates (not yet on release branch)

**Comment by thiakil** [comment]
Channel updates have been released. You'll need to run Shepherd with `--update` to overwrite any manual changes
