### ISSUE TITLE
Shepherd fails - top of the list

### ISSUE THREAD

**Issue by Arskin-Fertrubble** [ShephedProject/shepherd#29]
I'm seeing a lot of error exit codes in the log, which probably explains why I'm not seeing any EPG data in mythtv.

Top of the list is this, which is meaningless to me except for the word "FAIL".

> Appear to have previously downloaded Shepherd/MythTV.pm v0.42.
Testing reference Shepherd/MythTV.pm ... 
Executing: perl -e 'require "/home/pierre/.shepherd/references/Shepherd/MythTV.pm-0.42";'
Return value: 2
FAIL.

Any help on this?

Thanks.

**Comment by thiakil** [comment]
delete the file `/home/pierre/.shepherd/references/Shepherd/MythTV.pm-0.42` - it would appear the download is corrupted/incomplete.

Shepherd isn't checking that the checksum matches when the file exists (though it should)

**Comment by thiakil** [comment]
Should be fixed by 9e097803
