### ISSUE TITLE
symlink not created during --configure-mythtv process

### ISSUE THREAD

**Issue by kentcb** [ShephedProject/shepherd#32]
Hi,

Thanks for this software. I'm trying to get it running inside a Docker container using a separate system user called `shepherd`. When I run the configuration process, it seems like it's trying to do the right things but somehow failing to do so:

```
$ whoami
shepherd
$ pwd
/home/shepherd/.shepherd
$ ./tv_grab_au --configure-mythtv
shepherd v1.9.19 (linux)

Reading configuration file: /home/shepherd/.shepherd/shepherd.conf
Reading channels file: /home/shepherd/.shepherd/channels.conf

Configuring MythTV...

This will:
1. Create a symbolic link to Shepherd from tv_grab_au
2. Register Shepherd with MythTV as the default grabber
3. Turn off MythTV-driven scheduling of guide data updates
4. Turn off EIT
5. Create a cron job to periodically run Shepherd.

Step 1: Setting up symlink...
------

Shepherd would like to CREATE the following symlink:

 /usr/bin/tv_grab_au -> /home/shepherd/.shepherd/applications/shepherd/shepherd

Create symlink ? [yes,no (default=yes)] 
Symlink established:
total 64
drwxrwxr-x 3 shepherd shepherd  4096 Nov 25 10:58 applications
drwxrwxr-x 2 shepherd shepherd  4096 Nov 25 10:58 archive
-rw-rw-r-- 1 shepherd shepherd  1540 Nov 25 12:48 channels.conf
-rw-rw-r-- 1 shepherd shepherd    54 Nov 25 12:50 cron.bak
-rw-rw-r-- 1 shepherd shepherd    54 Nov 25 12:50 cron.new
drwxrwxr-x 7 shepherd shepherd  4096 Nov 25 10:58 grabbers
drwxrwxr-x 2 shepherd shepherd  4096 Nov 25 11:13 log
drwxrwxr-x 6 shepherd shepherd  4096 Nov 25 10:58 postprocessors
drwxrwxr-x 3 shepherd shepherd  4096 Nov 25 10:58 reconcilers
drwxrwxr-x 5 shepherd shepherd  4096 Nov 25 10:58 references
lrwxrwxrwx 1 shepherd shepherd    30 Nov 25 10:58 shepherd -> applications/shepherd/shepherd
-rw-rw-r-- 1 shepherd shepherd 22793 Nov 25 12:48 shepherd.conf
lrwxrwxrwx 1 shepherd shepherd    30 Nov 25 10:58 tv_grab_au -> applications/shepherd/shepherd

(further output snipped)

$ ls /usr/bin/tv_grab_au
ls: cannot access '/usr/bin/tv_grab_au': No such file or directory
```
This has later negative consequences for `mythfilldatabase`:

```
023-11-25 12:53:29.206827 E  tv_grab_au  --capabilities failed or we timed out waiting. You may need to upgrade your xmltv grabber
```

I can manually create the symlink as root:

```
$ whoami
root
$ ln -s /home/shepherd/.shepherd/tv_grab_au /usr/bin/tv_grab_au
```
After this, running `mythfilldatabase` works as expected.

According to the installation instructions, I can use a separate user without issue, but it seems to be causing a problem here. Am I doing something wrong, or is there an issue with the installation process?

**Comment by thiakil** [comment]
So is mythtv running inside the same docker container?
Running inside docker, Shepherd won't be able to create a symlink on your host system, so you will indeed need to set that up manually

**Comment by kentcb** [comment]
@thiakil Yes, it's in the same container (for now - I want to look at separating them once I get everything else working).

> Running inside docker, Shepherd won't be able to create a symlink on your host system

OK, interesting. I don't know enough about Linux/Docker to know why that would be the case, but good to know it's expected behavior.

**Comment by thiakil** [comment]
Nothing in the docker container is persistent except for mounted volumes and bind mounts to the host, so that's likely why you're seeing it not stick

Not being designed or tested on it, I don't advise using docker for Shepherd, though that symlink should be the only non-home write it does

**Comment by kentcb** [comment]
Every Docker container has its own file system layer, so all changes within that container are persisted. Of course, recreating the container will throw away those changes, but that's not something I'm doing.

The problem, as I think my original post shows in the log, is that attempting to create the symlink as the `shepherd` user is not working. If I create it as `root`, it works fine and continues to work fine even when I restart the container. I guess the reason I'm confused is I don't understand how the symlink would be created by a non-root user (or at least a user with write access to `/usr/bin/`) whether running under Docker or not.
