### ISSUE TITLE
custom output directory and filename

### ISSUE THREAD

**Issue by polyboi** [ShephedProject/shepherd#34]
Is it possible for the output xml go to a different directory and with a different name? I tried playing with the $output_filename and it worked but shepherd is now reporting that it's tainted and I got a "Use of uninitialized value in string eq at /usr/bin/tv_grab_au line 5176" message. Is there a best practice in how to implement this? Should I just be using a symlink in the location where I want the output to go?

**Comment by willat8** [comment]
Try using `shepherd --component-set shepherd:output=output.xmltv`.

**Comment by polyboi** [comment]
Thank you. I have set it up a bit differently now and wish to only output to STDOUT. Is there an option for this or will I need to modify the script?

**Comment by willat8** [comment]
Not sure if setting the output to /dev/stdout as per the above would work.
