### ISSUE TITLE
10 Bold rename to 10 Bold Drama

### ISSUE THREAD

**Issue by willat8** [ShephedProject/shepherd#36]
My 10 Bold data has disappeared, is this due to the rename to 10 Bold Drama?

**Comment by thiakil** [comment]
oh, goodness. again? probably

**Comment by HairySpoon** [comment]
But wait, there's more....

10 BOLD -> 10 BOLD Drama
10 Peach -> 10 Peach Comedy

ABC Kids/ABC TV Plus -> ABC Kids/ABC Family
ABC ME -> ABC Entertains

Hope this helps.

**Comment by Flic182** [comment]
Just to add to the fun...

TVSN has also moved from Seven's multiplex to Ten's (still an active channel).  In its place at Seven, a new channel has emerged - you.tv.

These may be largely pointless shopping channels, but I still hate seeing gaps in guide data.

Cheers.

**Comment by thiakil** [comment]
> Just to add to the fun...
> 
> TVSN has also moved from Seven's multiplex to Ten's (still an active channel). In its place at Seven, a new channel has emerged - you.tv.
> 
> These may be largely pointless shopping channels, but I still hate seeing gaps in guide data.
> 
> Cheers.

Did this happen to replace `IShopTV`?

**Comment by thiakil** [comment]
10s and ABCs have been renamed/migrated, you.tv added

NB: regions that have both TVSN **and** you.tv will need to migrate manually, Shepherd is not smart enough to do so automatically

**Comment by willat8** [comment]
Thanks @thiakil :)
