### ISSUE TITLE
Publishing code changes

### ISSUE THREAD

**Issue by perkins1724** [ShephedProject/shepherd#7]
What is the strategy for releasing code changes?

It looks like the three main branches are master, release and staging. Where is development intended to occur and how / when are changes being pushed to general release / general availability.

If the intention is for this repo to be the successor to whuffy I believe we should be avoiding breaking changes for the installed user base. What checks are being completed before changes are pushed to general release?

**Comment by thiakil** [comment]
I've been meaning to write this down in a readme and invite comments, sorry.

So far `master` is general development (trunk in svn terms), `staging` is for merging release changes and updating the status.csum, `release` should be only merges from staging once testing has been done.

Originally I just had master & release, but realised that could break things on the merge/update phase or perhaps things could be broken, so `staging` was born.

I have an install pointed at `staging` which i run an `--update` and grabber run on before merging to release usually.

**Comment by thiakil** [comment]
Should be solved with https://github.com/ShephedProject/shepherd/blob/master/CONTRIBUTING.md
